import { readFile, readdir, writeFile } from 'node:fs/promises';
import { resolve, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { rules, components, scenarios, uncovered } from './catalog.mjs';

export const root = fileURLToPath(new URL('../../', import.meta.url));
export const extension = resolve(root, 'browser-extension');
export const requireExtension = createRequire(resolve(extension, 'package.json'));
const postcss = requireExtension('postcss');
const generated = resolve(extension, 'docs/uiux/catalog.md');

export async function filesIn(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  return (await Promise.all(entries.map(entry => entry.isDirectory() ? filesIn(resolve(directory, entry.name)) : [resolve(directory, entry.name)]))).flat().sort();
}

export async function fingerprint(directory) {
  const hash = createHash('sha256');
  for (const path of await filesIn(directory)) hash.update(relative(directory, path)).update('\0').update(await readFile(path));
  return hash.digest('hex');
}

// Preview inputs are versioned separately so fixture-only edits do not rebuild the product.
export async function fixtureState(directory = root) {
  const files = ['agent-tool/ui.mjs', 'agent-tool/preview.mjs', 'agent-tool/gallery-preview.mjs', 'browser-extension/bridge/image-order.mjs'];
  for (const path of await filesIn(resolve(directory, 'browser-extension/tests'))) {
    if (path.endsWith('.browser.js')) files.push(relative(directory, path));
  }
  for (const path of await filesIn(resolve(directory, 'browser-extension/docs/gallery'))) files.push(relative(directory, path));
  files.sort();
  const hash = createHash('sha256');
  for (const file of files) hash.update(file).update('\0').update(await readFile(resolve(directory, file)));
  return { hash: hash.digest('hex'), files };
}

export async function sourceState() {
  const hash = createHash('sha256');
  for (const dir of ['entrypoints', 'lib', 'assets', 'public']) {
    for (const path of await filesIn(resolve(extension, dir))) {
      // icons are generated by prebuild from assets/brand; hash their input and generator.
      if (relative(extension, path).startsWith('public/icon/')) continue;
      hash.update(relative(extension, path)).update('\0').update(await readFile(path));
    }
  }
  for (const name of ['wxt.config.ts', 'package.json', 'package-lock.json', 'tsconfig.json', 'scripts/icons.mjs']) hash.update(name).update(await readFile(resolve(extension, name)));
  return {
    hash: hash.digest('hex'),
    revision: execFileSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8' }).trim(),
    dirty: !!execFileSync('git', ['status', '--porcelain'], { cwd: root, encoding: 'utf8' }).trim(),
  };
}

export async function tokens() {
  const entries = [];
  for (const path of await filesIn(resolve(extension, 'entrypoints'))) {
    if (!path.endsWith('.css')) continue;
    postcss.parse(await readFile(path, 'utf8'), { from: path }).walkDecls(/^--/, decl => {
      entries.push({ name: decl.prop, value: decl.value, selector: decl.parent.selector || decl.parent.name, file: relative(root, path), line: decl.source.start.line });
    });
  }
  return entries;
}

const cell = text => String(text).replaceAll('|', '\\|').replaceAll('\n', ' ');
const sourceLink = path => `[${path}](../../../${path})`;

export async function renderCatalog() {
  const known = new Set(rules.map(rule => rule.id));
  for (const item of [...rules, ...components]) {
    for (const path of item.sources || [item.source]) await readFile(resolve(root, path));
  }
  for (const scenario of scenarios) for (const id of scenario.rules) if (!known.has(id)) throw new Error(`Unknown rule ${id} in ${scenario.id}`);
  const output = ['# UIUX 可执行目录（生成文件）', '', '由 `node agent-tool/ui.mjs sync` 从规则目录和实际 CSS 生成；不要手工改数值。目录不代表全部项目规范已自动验证。', '', '## 规则与来源', '', '| ID | 规则 / 意图 | 表面 | 源码 |', '| --- | --- | --- | --- |'];
  for (const rule of rules) output.push(`| ${rule.id} | ${rule.title}：${rule.intent} | ${rule.surfaces.join(', ')} | ${rule.sources.map(sourceLink).join('、')} |`);
  output.push('', '## 组件复用入口', '', '| 组件 | 用法 | 源码 |', '| --- | --- | --- |');
  for (const component of components) output.push(`| ${component.name} | ${component.use} | ${sourceLink(component.source)} |`);
  output.push('', '## 可重现场景', '', '| ID | 表面 / 视口 | 状态 | 检查 |', '| --- | --- | --- | --- |');
  for (const scenario of scenarios) output.push(`| ${scenario.id} | ${scenario.surface} ${scenario.viewport.width}×${scenario.viewport.height} | ${scenario.path}${scenario.prepare ? ' / ' + scenario.prepare : ''} | ${scenario.regression || scenario.rules.join(', ')} |`);
  output.push('', '## CSS 变量清单', '', '这是声明清单，包含状态/媒体查询覆盖；同名变量有不同作用域，不代表每个数值都可全局复用。CSS 是数值唯一来源。', '', '| 变量 | 值 | 选择器 | 来源行 |', '| --- | --- | --- | --- |');
  for (const token of await tokens()) output.push(`| ${cell(token.name)} | ${cell(token.value)} | ${cell(token.selector)} | ${sourceLink(token.file)}:${token.line} |`);
  output.push('', '## 覆盖边界', '', ...uncovered.map(text => `- ${text}`), '');
  return output.join('\n');
}

export async function syncCatalog(check = false) {
  const content = await renderCatalog();
  if (check) {
    const saved = await readFile(generated, 'utf8').catch(() => '');
    if (content !== saved) throw new Error('UIUX 目录已过期：运行 node agent-tool/ui.mjs sync，复核生成差异。此命令不更新视觉基线。');
  } else await writeFile(generated, content);
  return { file: relative(root, generated), current: true, written: !check };
}

export async function contextFor(files = []) {
  const normalized = files.map(file => {
    const path = relative(root, resolve(root, file));
    if (path.startsWith('..' + sep) || path === '..') throw new Error(`文件不在仓库内：${file}`);
    return path;
  });
  const matched = rules.filter(rule => rule.sources.some(source => normalized.includes(source)));
  // Static-rule sources describe ownership, not a complete graph of UI consumers.
  const fallback = !normalized.length || matched.some(rule => rule.kind === 'static') || normalized.some(file => !rules.some(rule => rule.sources.includes(file)));
  const selected = fallback ? rules : matched;
  const selectedIds = new Set(selected.map(rule => rule.id));
  return {
    files: normalized, fullCoverageFallback: fallback,
    reason: fallback ? '共享/未知依赖没有完整影响图，回退全部登记场景，不静默跳过。' : '直接来源匹配；仍需复核业务交叉影响。',
    rules: selected, components,
    scenarios: scenarios.filter(scenario => scenario.regression || scenario.rules.some(id => selectedIds.has(id))),
    tokens: await tokens(), uncovered,
  };
}

// Development order only. Final gate never consumes this selection to omit scenarios.
export async function planFor(files) {
  const context = await contextFor(files);
  const riskIds = ['end-to-end-keyboard-workspace-failure', 'end-to-end-keyboard-popup-failure', 'end-to-end-generation-failed'];
  // Only this dedicated stylesheet has reviewed, bounded consumer coverage. Rule
  // ownership alone does not map business effects of workspace/shared components.
  const coverageUncertain = context.fullCoverageFallback || context.files.length !== 1 || context.files[0] !== 'browser-extension/entrypoints/popup/image-viewer.css';
  const selected = coverageUncertain ? scenarios : scenarios.filter(scene => (!scene.regression && context.scenarios.some(item => item.id === scene.id)) || riskIds.includes(scene.id));
  return {
    files: context.files, coverageUncertain,
    reason: coverageUncertain ? '业务影响映射不完整或输入范围不唯一，建议全部登记场景；规则来源匹配不等于完整业务依赖图。' : '专用 image-viewer.css 的已核实消费者场景，加键盘/失败恢复风险；变更超出局部样式职责时仍须扩大复核。',
    purpose: 'Development feedback and early risk review only; final browser/full gate remains complete.',
    scenarios: selected.map(scene => scene.id), requiredRiskScenarios: riskIds,
    command: 'node agent-tool/ui.mjs verify --no-build --scenarios ' + selected.map(scene => scene.id).join(' ') + ' --reason development-feedback',
    finalCommand: 'node agent-tool/ui.mjs gate --tier browser --no-build --reason final-validation',
    uncovered: context.uncovered,
  };
}
