// Production settings UI, synthetic messages only; no credentials or API calls.
const wait = async predicate => {
  const end = Date.now() + 6000;
  while (!predicate()) { if (Date.now() > end) throw new Error('等待生图设置超时'); await new Promise(resolve => setTimeout(resolve, 20)); }
};
const assert = (value, message) => { if (!value) throw new Error(message); };
const section = () => document.querySelector('.image-generation-settings');
const input = type => section()?.querySelector(`input${type ? `[type="${type}"]` : ':not([type])'}`);
const fill = (node, value) => { Object.getOwnPropertyDescriptor(node instanceof HTMLSelectElement ? HTMLSelectElement.prototype : HTMLInputElement.prototype, 'value').set.call(node, value); node.dispatchEvent(new Event(node instanceof HTMLSelectElement ? 'change' : 'input', { bubbles: true })); };
const open = async () => { document.querySelector('[aria-label="设置中心"]').click(); await wait(() => document.querySelector('.settings-center-nav')); [...document.querySelectorAll('.settings-center-nav button')].find(button => button.textContent === '生图渠道').click(); };
const scenario = new URLSearchParams(location.search).get('imageSettingsRegression');
try {
  await wait(() => document.querySelector('.connection-state')?.textContent.includes('已连接'));
  await open(); await wait(section);
  if (scenario === 'legacy') {
    await wait(() => section().querySelector('[role="alert"]'));
    assert(section().textContent.includes('更新并重启本机服务'), '旧服务应显示明确升级说明');
    assert(section().querySelector('select').disabled, '读取失败不能覆盖设置');
  } else {
    await wait(() => !section().querySelector('select').disabled);
    assert(section().querySelector('select').value === 'codex', '旧配置默认 Codex');
    assert(!section().querySelector('.model-settings') && !section().textContent.includes('验证并使用') && !section().textContent.includes('管理 Codex CLI'), '内置生图不展示文字模型配置或管理入口');
    fill(section().querySelector('select'), 'openai'); await wait(() => input('url'));
    fill(input('url'), 'https://images.example/v1'); fill(input(), 'fixture-image'); fill(input('password'), 'fixture-secret');
    section().querySelector('.primary').click();
    await wait(() => section().querySelector('[role="alert"]'));
    assert(input('password').value === 'fixture-secret', '失败保留输入以便重试');
    assert(section().textContent.includes('当前使用：Codex'), '保存失败保持原渠道');
    section().querySelector('.primary').click();
    await wait(() => section().textContent.includes('已保存，用于之后提交'));
    assert(input('password').value === '', '保存成功立即清空输入密钥');
    assert(section().textContent.includes('当前使用：OpenAI'), '保存成功显示实际渠道');
    document.querySelector('[aria-label="关闭设置"]').click(); await wait(() => !section());
    await open(); await wait(() => input('url'));
    assert(input('url').value === 'https://images.example/v1' && input().value === 'fixture-image', '重开恢复地址与模型');
    assert(input('password').value === '' && section().textContent.includes('已保存密钥'), '重开只读取密钥存在状态');
    fill(section().querySelector('select'), 'gemini'); await wait(() => input('url').value.includes('googleapis'));
    assert(input('password').value === '', '切换供应商不得带入密钥');
    fill(input(), 'gemini-fixture'); fill(input('password'), 'gemini-secret');
    section().querySelector('.primary').click(); await wait(() => section().textContent.includes('当前使用：Gemini'));
    section().querySelector('button[type="button"]').click(); await wait(() => section().textContent.includes('API Key 已清除'));
    assert(section().textContent.includes('尚未保存密钥'), '清除成功可观察');
    fill(section().querySelector('select'), 'magpie'); await wait(() => input('url').value.includes('3425'));
    assert(!input('password'), 'Magpie 不索要供应商密钥');
    await wait(() => section().textContent.includes('找到 1 个生图模型'));
    assert(section().querySelector('.primary').disabled, '首次自动加载不自动选择或保存模型');
    const connect = () => section().querySelector('button[type="button"]');
    const modelSelect = () => section().querySelector('[aria-label="生图模型"]');
    fill(input('url'), 'http://127.0.0.1:3428');
    await wait(() => section().textContent.includes('没有可用的生图模型'));
    assert(modelSelect().disabled && section().querySelector('.primary').disabled && !connect().disabled, '空目录明确提示并可刷新，不能误保存');
    fill(input('url'), 'http://127.0.0.1:3430');
    await wait(() => section().querySelector('#magpie-model-status')?.textContent.includes('更新并重启本机服务'));
    assert(section().querySelector('.primary').disabled, '旧桥接缺目录接口时不能误保存');
    fill(input('url'), 'http://127.0.0.1:3427');
    await wait(() => section().querySelector('[role="alert"]'));
    assert(section().querySelector('#magpie-model-status').getAttribute('role') === 'alert' && section().querySelector('.primary').disabled, '连接失败在模型旁提示并禁止保存');
    connect().click(); await wait(() => connect().disabled);
    assert(modelSelect().disabled && section().querySelector('.primary').disabled, '读取期间不能选择或保存');
    await wait(() => !connect().disabled);
    fill(input('url'), 'http://127.0.0.1:3426');
    await wait(() => connect().disabled);
    await new Promise(resolve => setTimeout(resolve, 300));
    fill(input('url'), 'http://127.0.0.1:3425');
    await wait(() => section().textContent.includes('找到 1 个生图模型'));
    await new Promise(resolve => setTimeout(resolve, 700));
    assert(![...modelSelect().options].some(option => option.value === 'old/image'), '旧地址迟到目录不能覆盖新连接');
    fill(modelSelect(), 'fixture/image'); section().querySelector('.primary').click();
    await wait(() => section().querySelector('[role="alert"]'));
    assert(modelSelect().value === 'fixture/image' && section().textContent.includes('当前使用：Gemini'), 'Magpie 保存失败保留输入和原渠道');
    section().querySelector('.primary').click(); await wait(() => section().textContent.includes('当前使用：Magpie'));
    document.querySelector('[aria-label="关闭设置"]').click(); await wait(() => !section());
    await open(); await wait(() => modelSelect()?.value === 'fixture/image');
    await wait(() => !modelSelect().disabled);
    assert(!input('password') && section().textContent.includes('网关默认尺寸'), '重开保留 Magpie，并明确尺寸和能力边界');
    assert(!section().querySelector('.primary').disabled, '重开自动加载并核对已保存模型');
    fill(input('url'), 'http://127.0.0.1:3426'); await wait(() => connect().disabled);
    await new Promise(resolve => setTimeout(resolve, 300));
    document.querySelector('[aria-label="关闭设置"]').click(); await wait(() => !section());
    await open(); await wait(() => modelSelect()?.value === 'fixture/image' && !modelSelect().disabled);
    await new Promise(resolve => setTimeout(resolve, 700));
    assert(input('url').value.endsWith(':3425') && ![...modelSelect().options].some(option => option.value === 'old/image'), '关闭再打开后不能接收旧面板目录或覆盖已保存选择');
    fill(input('url'), 'http://127.0.0.1:3429'); await wait(() => !modelSelect().disabled);
    assert(modelSelect().value === '' && section().querySelector('.primary').disabled, '地址变化后不带入旧地址选择');
    fill(modelSelect(), 'fixture/image'); section().querySelector('.primary').click();
    await wait(() => section().textContent.includes('已保存，用于之后提交') && !modelSelect().disabled);
    document.querySelector('[aria-label="关闭设置"]').click(); await wait(() => !section());
    await open(); await wait(() => section()?.textContent.includes('已选模型不在当前目录'));
    assert(modelSelect().value === 'fixture/image' && section().querySelector('.primary').disabled, '失效的已保存模型保留展示但不能保存');
    assert([...modelSelect().options].some(option => option.value === 'fixture/replacement'), '失效模型可由用户重新选择，不能自动换模型');
    fill(input('url'), 'http://127.0.0.1:3426'); await wait(() => connect().disabled);
    await new Promise(resolve => setTimeout(resolve, 300));
    fill(section().querySelector('select'), 'openai'); await wait(() => input('password'));
    await new Promise(resolve => setTimeout(resolve, 700));
    assert(input().value === 'fixture-image' && section().textContent.includes('已保存密钥'), 'Magpie 不改写旧渠道配置');
    assert(!section().querySelector('#magpie-model-status'), '切换渠道后迟到目录不能泄漏到其他渠道');
    fill(section().querySelector('select'), 'magpie'); await wait(() => section().textContent.includes('已选模型不在当前目录'));
    assert(document.querySelector('.settings-center-content').scrollWidth <= document.querySelector('.settings-center-content').clientWidth + 1, '窄屏不能横向溢出');
  }
  document.documentElement.dataset.imageSettingsRegression = 'passed';
  document.querySelector('#preview-notice').textContent = '生图设置回归：PASS';
} catch (error) {
  document.documentElement.dataset.imageSettingsRegression = 'failed';
  document.querySelector('#preview-notice').textContent = `生图设置回归：FAIL · ${error.message}`;
  console.error(error);
}
